runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/images/favicon.ico
- url: /.*
  script: main.app

libraries:
- name: ssl
  version: 2.7.11
